config/routes.rb
Cities::Application.routes.draw do
  get "choice/check"
  get "choice/result"
  get "cities/import" 

  resources :cities

  root :to => 'cities#index'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  attr_accessible :costs, :education, :environment, :security, :transportation, :resultsjson



  def results; JSON.parse(self.resultsjson); end

  def results=(value); self.resultsjson = value.to_json; end

  def save_the_results( value )
   self.resultsjson = value.to_json
  end
  #
  #

  #def nir( bla )
    #:resultsjson = bla.to_json
  #end

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :costs, :education, :name, :enviornment, :security, :transportation
  validates :name, :presence => true
  validates :costs, :education, :enviornment, :security,
    :inclusion => { :in => 0..100, :message => "value must be betwene 1 and 20" } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/choice_controller.rb
class ChoiceController < ApplicationController
  def check
    @city = City.new
  end

  def result
    @city = City.new
    save_choice_to_db
    @draws = []

    Choice.find(:all, :limit => 10, :order=> 'created_at desc').each do | choice | 
      @draws.push( draw_for( choice ) )
    end
    render "result"
  end


  def draw_for( choice )
    grades_charts = {}
    grades = []

    choice.results.each do | grade | 
      grades.push( grade )
      grades_charts[ grade[0] ] = grade[1]
    end


    draw = {}

    draw['choice'] = choice
    draw['grades'] = grades
    draw['grades_charts'] = grades_charts
    draw
  end

  def save_choice_to_db
    if params['city'] == nil 
      return params['city'] 
    end
    choice = Choice.new

    user_choice = normalise_choice( params['city'] )
    

    user_choice.each do |criteria|  
      choice[ criteria[0] ] = user_choice[ criteria[0] ]    
    end



    results = {}
    cities_grades( user_choice ).each do | grade |
      results[ grade[0].name] = grade[1]
    end

    choice.save_the_results( results )
    choice.save
  end


  def normalise_choice( user_choice )
    sum = 0 
    user_choice.each do | item | 
      sum += Integer( item[1] ) 
    end


    result = {}
    proportion = sum / 100.0 

    user_choice.each do | item | 
      result[ item[0]] = Integer( item[1] ) / proportion
    end
    result
  end

  def cities_grades( user_proportions )
    cities_grades = {}
    City.all.each do | city |
      cities_grades[ city ] = city_grade( city, user_proportions )
    end
    cities_grades
  end


  def city_grade( city, user_proportions )
    if user_proportions != nil  
      result = 0
      user_proportions.keys.each do |pr| 
        result += Integer(city[pr]) * Integer(user_proportions[pr]) 
      end
      result
    end

  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])

    @chart_dict  = {}

    City.accessible_attributes.each do | attr | 
      if attr != "" and attr != "name"
        @chart_dict[ attr ] = @city[attr]
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end


  def import

    City.delete_all
    require 'csv'    

    csv_text = File.read('/Users/nirnaori/projects/cities/lib/assets/cities_grades.csv')


    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
      new_city = City.create
      new_city.name = row['name']
      new_city.transportation = row['transportation']
      new_city.education = row['education']
      new_city.costs = row['costs']
      new_city.security = row['security']
      new_city.enviornment = row['enviornment']
      new_city.save

      print row

    end

    index
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choice_helper.rb
module ChoiceHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/choice/_check.html.erb
<p>Please state the priority you want for your city to live</p>

<%= form_for @city , :url => choice_result_path, :method => "get" do |f|  %>
</h2>

  <%= f.label :costs %>
  <%= f.number_field :costs %><br />

  <%= f.label :education %> 
  <%= f.number_field :education %><br />

  <%= f.label :enviornment %>
  <%= f.number_field :enviornment %><br />

  <%= f.label :security %>
  <%= f.number_field :security %><br />
  

  <%= f.label :transportation %>
  <%= f.number_field :transportation %><br />
  <label id="sum">Total: </label>


  <%= f.submit value="Calculate" %>
<% end %>

app/views/choice/check.html.erb
<%= render "check" %>

app/views/choice/result.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<%= render "check" %>

<input class="filterInteresting" type="checkbox"> Show Only interesting choices

<% @draws.each do |draw| %>

  <div class = "draw">


    <div class="choiceparams">
      <ul>
        <li>
          <label> Costs <%= draw['choice'].costs%> 
        </li>
        <li>
          <label> Education <%= draw['choice'].education %> 
        </li>
        <li>
          <label> Environment <%= draw['choice'].enviornment %> 
        </li>
        <li>
          <label> Secutiry <%= draw['choice'].security %> 
        </li>
        <li>
          <label> Transportation <%= draw['choice'].transportation %> 
        </li>
      </ul>
      <input class="interesting" type="checkbox" value="bla"> 
      <label id="interestinglabel" > Looks interesting </label> 
    </div>


    <div class ="charts">
        <%= column_chart draw['grades_charts'] %>
    </div>

  </div>

<% end %>

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :transportation %><br />
    <%= f.number_field :transportation %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.number_field :education %>
  </div>
  <div class="field">
    <%= f.label :costs %><br />
    <%= f.number_field :costs %>
  </div>
  <div class="field">
    <%= f.label :security %><br />
    <%= f.number_field :security %>
  </div>
  <div class="field">
    <%= f.label :enviornment %><br />
    <%= f.number_field :enviornment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Transportation</th>
    <th>Education</th>
    <th>Costs</th>
    <th>Security</th>
    <th>Environment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= city.transportation %></td>
    <td><%= city.education %></td>
    <td><%= city.costs %></td>
    <td><%= city.security %></td>
    <td><%= city.enviornment %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>
<%= link_to "Set your priorities", choice_check_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @city.name %>
</p>

<p>
  <b>Costs:</b>
  <%= @city.costs %>
</p>

<p>
  <b>Education:</b>
  <%= @city.education %>
</p>

<p>
  <b>Environment:</b>
  <%= @city.enviornment %>
</p>

<p>
  <b>Security:</b>
  <%= @city.security %>
</p>

<p>
  <b>Transportation:</b>
  <%= @city.transportation %>
</p>






<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

<div class ="charts">
    <%= pie_chart @chart_dict %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cities</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">City prioritiser</a>
    <ul class="nav">
      <li class="<%= 'active' if current_page?(cities_path) %>">
        <%= link_to 'All Cities', cities_path %>
      </li>
      <li class="<%= 'active' if current_page?(choice_check_path ) %>">
        <%= link_to "Prioritise", choice_check_path %>
      </li>
      <li class="<%= 'active' if current_page?(choice_result_path ) %>">
        <%= link_to "History", choice_result_path  %>
      </li>
    </ul>
  </div>
</div>

<%= yield %>

</body>
</html>